dist: xenial
language: python
cache: pip
python:
- 3.5
- 3.6
- 3.7
before_install:
- echo ===================pitchpx testing start============================
script:
- py.test ./tests
after_success:
- echo ===================pitchpx testing end==============================
